import { ArrowLeft } from "lucide-react-native";
import React, { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import type { RemoteInput } from "../../lib/ws";
import { useTokens } from "../../theme/ThemeProvider";
import { radii, space } from "../../theme/tokens";
import { formatCost, formatTokenPair, type as typeScale } from "../../theme/typography";
import { ContextGauge } from "../ds/ContextGauge";
import { Sheet } from "../ds/Sheet";
import { EFFORT_LEVELS, type EffortLevel } from "./EffortPicker";

export function TelemetrySheet({ visible, onClose, tier, model, temper, effort, send, costUsd, contextTokens, contextLimit, weekly }: { visible: boolean; onClose: () => void; tier: string | null; model: string; temper: string; effort?: string | null; send: (input: RemoteInput) => boolean; costUsd: number; contextTokens: number; contextLimit: number | null; weekly?: { provider: string; deltaPct: number } | null; }) {
  const tokens = useTokens();
  const [pane, setPane] = useState<"telemetry" | "effort">("telemetry");
  const current = EFFORT_LEVELS.includes(effort as EffortLevel) ? effort as EffortLevel : null;
  const contextPercent = contextLimit != null && contextLimit > 0 ? Math.min(100, (contextTokens / contextLimit) * 100) : null;
  const close = () => { setPane("telemetry"); onClose(); };
  const run = (command: string) => { if (send({ kind: "prompt", text: command })) close(); };
  const selectEffort = (level: EffortLevel | null) => run(level ? `/effort ${level}` : "/effort");

  return <Sheet visible={visible} onClose={close} accessibilityLabel={pane === "effort" ? "Reasoning effort" : "Session telemetry"} snapPoints={[0.82]}><View style={styles.content}>
    {pane === "effort" ? <>
      <Pressable onPress={() => setPane("telemetry")} accessibilityRole="button" accessibilityLabel="Back to session telemetry" style={styles.back}><ArrowLeft size={18} color={tokens.accent} /><Text style={[typeScale.bodyBold, { color: tokens.accent }]}>Session telemetry</Text></Pressable>
      <Text style={[typeScale.heading, { color: tokens.ink }]}>Reasoning effort</Text>
      <Text style={[typeScale.sub, { color: tokens.ink3 }]}>Choose how intensely Forge reasons for this session.</Text>
      <View accessibilityRole="radiogroup" accessibilityLabel="Reasoning effort options" style={[styles.surface, { backgroundColor: tokens.bg3, borderColor: tokens.border }]}>{[null, ...EFFORT_LEVELS].map((level) => { const selected = level === current; const label = level ?? "default"; return <Pressable key={label} onPress={() => selectEffort(level)} accessibilityRole="radio" accessibilityState={{ selected }} style={[styles.effort, { borderColor: selected ? tokens.accent : tokens.border, backgroundColor: selected ? tokens.selection : "transparent" }]}><Text style={[typeScale.bodyBold, { color: level === "whitehot" ? tokens.accent : tokens.ink }]}>{label}</Text><Text style={[typeScale.meta, { color: selected ? tokens.accent : tokens.ink3 }]}>{selected ? "selected" : "Choose"}</Text></Pressable>; })}</View>
    </> : <>
      <Text style={[typeScale.heading, { color: tokens.ink }]}>Session telemetry</Text><Text style={[typeScale.sub, { color: tokens.ink3 }]}>Context, routing, and reasoning controls for this session.</Text>
      <Section title="Context"><View style={[styles.surface, { backgroundColor: tokens.bg3, borderColor: tokens.border }]}>{contextLimit != null ? <><ContextGauge used={contextTokens} total={contextLimit} /><View style={styles.pair}><Text style={[typeScale.bodyBold, { color: contextPercent != null && contextPercent >= 90 ? tokens.danger : tokens.ink }]}>{`${contextPercent?.toFixed(0)}% used`}</Text><Text style={[typeScale.meta, { color: tokens.ink3 }]}>{formatTokenPair(contextTokens, contextLimit)}</Text></View><Text style={[typeScale.meta, { color: tokens.ink3 }]}>{`${Math.max(0, contextLimit - contextTokens).toLocaleString()} tokens remain before Forge compacts.`}</Text></> : <Text style={[typeScale.body, { color: tokens.ink3 }]}>Context capacity is unavailable for this model.</Text>}</View><Action label="Compact context" detail="Summarize earlier conversation to free capacity" onPress={() => run("/compact")} /><Action label="Restore compacted context" detail="Bring back the previous full conversation" onPress={() => run("/uncompact")} quiet /></Section>
      <Section title="Quota"><View style={[styles.surface, { backgroundColor: tokens.bg3, borderColor: tokens.border }]}>{weekly ? <><Text style={[typeScale.bodyBold, { color: tokens.success }]}>{`≈ +${weekly.deltaPct.toFixed(1)}% weekly quota`}</Text><Text style={[typeScale.meta, { color: tokens.ink3 }]}>This session&apos;s estimated share of {weekly.provider}.</Text></> : <><Text style={[typeScale.bodyBold, { color: tokens.success }]}>{`cost ${formatCost(costUsd)}`}</Text><Text style={[typeScale.meta, { color: tokens.ink3 }]}>Metered API cost recorded for this session.</Text></>}</View></Section>
      <Section title="Model configuration"><View style={[styles.surface, { backgroundColor: tokens.bg3, borderColor: tokens.border }]}>{tier ? <Value label="Tier" value={tier} /> : null}<Action label="Model" detail={model} onPress={() => run("/model")} compact /><Action label="Operating mode" detail={temper} onPress={() => run("/mode")} compact /></View><Action label="Explain mesh routing" detail="See why Forge chose this model" onPress={() => run("/mesh")} /></Section>
      <Section title="Reasoning effort"><View style={[styles.surface, { backgroundColor: tokens.bg3, borderColor: tokens.border }]}><Value label="Current effort" value={current ?? "default"} /><Action label="Change reasoning effort" detail="Choose how intensely Forge reasons" onPress={() => setPane("effort")} /></View></Section>
    </>}
  </View></Sheet>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { const tokens = useTokens(); return <View style={styles.section}><Text style={[typeScale.meta, styles.sectionTitle, { color: tokens.ink3 }]}>{title}</Text>{children}</View>; }
function Value({ label, value }: { label: string; value: string }) { const tokens = useTokens(); return <View style={styles.value}><Text style={[typeScale.meta, { color: tokens.ink3 }]}>{label}</Text><Text style={[typeScale.bodyBold, styles.valueText, { color: tokens.ink }]} numberOfLines={1}>{value}</Text></View>; }
function Action({ label, detail, onPress, quiet = false, compact = false }: { label: string; detail: string; onPress: () => void; quiet?: boolean; compact?: boolean }) { const tokens = useTokens(); return <Pressable onPress={onPress} accessibilityRole="button" style={[styles.action, compact && styles.compactAction, { backgroundColor: compact ? "transparent" : quiet ? tokens.bg2 : tokens.bg3, borderColor: tokens.border }]}><Text style={[typeScale.bodyBold, { color: quiet || compact ? tokens.ink2 : tokens.accent }]}>{label}</Text><Text style={[typeScale.meta, { color: tokens.ink3 }]} numberOfLines={1}>{detail}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: space.space16, paddingBottom: space.space32, gap: space.space16 }, back: { alignSelf: "flex-start", minHeight: 44, flexDirection: "row", alignItems: "center", gap: space.space4 }, section: { gap: space.space8 }, sectionTitle: { letterSpacing: 0.7, textTransform: "uppercase" }, surface: { gap: space.space8, padding: space.space12, borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.radius12 }, pair: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", gap: space.space8 }, value: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: space.space12 }, valueText: { flexShrink: 1, textAlign: "right" }, action: { minHeight: 44, justifyContent: "center", gap: 2, paddingHorizontal: space.space12, borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.radius8 }, compactAction: { paddingHorizontal: 0, borderWidth: 0, borderRadius: 0 }, effort: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: space.space12, borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.radius8 } });
