#!/usr/bin/env bash
# Fails the build if the prebuilt iOS project would ship push-broken entitlements.
#
# Run AFTER `expo prebuild -p ios`, from the `mobile/` directory (see ios/ci_scripts/
# ci_post_clone.sh). prebuild regenerates entitlements from app.config.ts on every build and
# deletes anything it does not own, so a fix applied by hand to the generated project — which is
# exactly what was tried before, a separate Forge.Release.entitlements wired into the Release
# configuration — is silently reverted and never reaches an archive.
#
# The failure this guards is invisible from the outside: expo-notifications' plugin writes
# `aps-environment: development`, EAS Build would rewrite it to `production` from the signing
# credentials, and Xcode Cloud does not. A distribution build carrying `development` still installs
# and still shows its notification permission as granted in iOS Settings, but
# `getDevicePushTokenAsync()` rejects, so push can never be enabled.
set -euo pipefail

entitlements=ios/Forge/Forge.entitlements

if [[ ! -f $entitlements ]]; then
  echo "verify-ios-entitlements: $entitlements is missing — did prebuild run, and from mobile/?" >&2
  exit 1
fi

read_key() {
  /usr/libexec/PlistBuddy -c "Print :$1" "$entitlements" 2>/dev/null || true
}

aps=$(read_key 'aps-environment')
if [[ $aps != production ]]; then
  echo "verify-ios-entitlements: aps-environment is '${aps:-<absent>}', expected 'production'." >&2
  echo "  Declare it in mobile/app.config.ts under ios.entitlements — editing the generated" >&2
  echo "  project does not survive prebuild. Push cannot be enabled in a build without it." >&2
  exit 1
fi

# The widget extension and the app share state through this group; losing it breaks the Home Screen
# widget and the Live Activity rather than push, but it is regenerated by the same mechanism and is
# just as invisible when absent.
groups=$(read_key 'com.apple.security.application-groups')
if [[ $groups != *group.dev.adulari.forge* ]]; then
  echo "verify-ios-entitlements: app group 'group.dev.adulari.forge' missing from $entitlements." >&2
  exit 1
fi

echo "verify-ios-entitlements: aps-environment=production, app group present."
