#!/usr/bin/env bash
# Fails the build if the prebuilt iOS project would ship push-broken entitlements or a share
# extension that cannot hand content back to the main app.
#
# Run AFTER `expo prebuild -p ios`, from the `mobile/` directory (see ios/ci_scripts/
# ci_post_clone.sh). prebuild regenerates entitlements from app.config.ts on every build and
# deletes anything it does not own, so a fix applied by hand to the generated project — which is
# exactly what was tried before, a separate Forge.Release.entitlements wired into the Release
# configuration — is silently reverted and never reaches an archive.
#
# The failure this guards is invisible from the outside: expo-notifications' plugin writes
# `aps-environment: development`, EAS Build would rewrite it to `production` from the signing
# credentials, and Xcode Cloud does not. A distribution build carrying `development` still installs
# and still shows its notification permission as granted in iOS Settings, but
# `getDevicePushTokenAsync()` rejects, so push can never be enabled.
set -euo pipefail

entitlements=ios/Forge/Forge.entitlements
app_info=ios/Forge/Info.plist
project=ios/Forge.xcodeproj/project.pbxproj
share_dir=ios/expo-sharing-extension
share_entitlements=$share_dir/expo-sharing-extension.entitlements
share_info=$share_dir/Info.plist
app_group=group.dev.adulari.forge

read_key() {
  local file=$1
  local key=$2
  if [[ -x /usr/libexec/PlistBuddy ]]; then
    /usr/libexec/PlistBuddy -c "Print :$key" "$file" 2>/dev/null || true
    return
  fi
  # Linux prebuild verification has no PlistBuddy. `plist` is an Expo transitive dependency
  # installed by mobile/npm ci, so use it only as the portable read-only fallback.
  node - "$file" "$key" <<'NODE' 2>/dev/null || true
const fs = require("node:fs");
const plist = require("plist");
const [file, key] = process.argv.slice(2);
let value = plist.parse(fs.readFileSync(file, "utf8"));
for (const segment of key.split(":")) value = value?.[segment];
if (Array.isArray(value)) process.stdout.write(`${value.join("\n")}\n`);
else if (value !== undefined && value !== null) process.stdout.write(`${String(value)}\n`);
NODE
}

for required in "$entitlements" "$app_info" "$project" "$share_entitlements" "$share_info"; do
  if [[ ! -f $required ]]; then
    echo "verify-ios-entitlements: $required is missing — did prebuild run, and from mobile/?" >&2
    exit 1
  fi
done

aps=$(read_key "$entitlements" 'aps-environment')
if [[ $aps != production ]]; then
  echo "verify-ios-entitlements: aps-environment is '${aps:-<absent>}', expected 'production'." >&2
  echo "  Declare it in mobile/app.config.ts under ios.entitlements — editing the generated" >&2
  echo "  project does not survive prebuild. Push cannot be enabled in a build without it." >&2
  exit 1
fi

# The widget extension and the app share state through this group; losing it breaks the Home Screen
# widget and the Live Activity rather than push, but it is regenerated by the same mechanism and is
# just as invisible when absent.
groups=$(read_key "$entitlements" 'com.apple.security.application-groups')
if [[ $groups != *"$app_group"* ]]; then
  echo "verify-ios-entitlements: app group '$app_group' missing from $entitlements." >&2
  exit 1
fi

# expo-sharing's iOS extension and the main app communicate only through this App Group plus the
# ExpoShareIntoAppGroupId marker. A generated extension can compile and appear in the share sheet
# while silently failing to hand off content if either side drifts.
share_groups=$(read_key "$share_entitlements" 'com.apple.security.application-groups')
if [[ $share_groups != *"$app_group"* ]]; then
  echo "verify-ios-entitlements: app group '$app_group' missing from $share_entitlements." >&2
  exit 1
fi

handoff_group=$(read_key "$app_info" 'ExpoShareIntoAppGroupId')
if [[ $handoff_group != "$app_group" ]]; then
  echo "verify-ios-entitlements: ExpoShareIntoAppGroupId is '${handoff_group:-<absent>}', expected '$app_group'." >&2
  exit 1
fi

if ! grep -Fq 'PRODUCT_BUNDLE_IDENTIFIER = dev.adulari.forge.sharing;' "$project"; then
  echo "verify-ios-entitlements: share-extension bundle id dev.adulari.forge.sharing is missing from $project." >&2
  exit 1
fi

supports_text=$(read_key "$share_info" 'NSExtension:NSExtensionAttributes:NSExtensionActivationRule:NSExtensionActivationSupportsText')
web_url_count=$(read_key "$share_info" 'NSExtension:NSExtensionAttributes:NSExtensionActivationRule:NSExtensionActivationSupportsWebURLWithMaxCount')
display_name=$(read_key "$share_info" 'CFBundleDisplayName')
if [[ $supports_text != true || $web_url_count != 1 || $display_name != Forge ]]; then
  echo "verify-ios-entitlements: share config is text='${supports_text:-<absent>}' web-url-count='${web_url_count:-<absent>}' display-name='${display_name:-<absent>}', expected true/1/Forge." >&2
  exit 1
fi
if ! grep -Fq 'INFOPLIST_KEY_CFBundleDisplayName = Forge;' "$project"; then
  echo "verify-ios-entitlements: the share target build settings do not preserve display name Forge." >&2
  exit 1
fi

echo "verify-ios-entitlements: production APNs and text/URL share-extension handoff are configured."
